### ISSUE TITLE
Inclusion of ee5_base64 code into APRIL-ANN project

### ISSUE THREAD

**Issue by pakozm** [ErnieE5/ee5_base64#1]
Dear Ernie, I have introduced today ee5_base64 into our base code for APRIL-ANN, a toolkit for machine learning and pattern recognition tasks. I would like to ask your permission to do so, your project has been cited into our README.md and the source code copyright is "as is" in your file:
https://github.com/pakozm/april-ann/blob/devel/packages/basics/ee5_base64/lua_src/ee5_base64.lua

Many thanks for your valuable work :-)

**Comment by ErnieE5** [comment]
Thank you for letting me know. :-) I hope that it brings value to your project. It made a huge impact to the code it replaced and keeping it natural Lua made it easier to distribute.
